const sections = [
  {title:'1. Eligibility', body:['Customer must be at least 21 years of age, or meet the minimum age requirement applicable to the selected vehicle category.','Customer must hold a valid and legally accepted driving licence, provide valid government-issued identity and address proof, and complete the required verification process before vehicle handover.','Ride Aura Self Drive reserves the right to accept or reject a booking if the customer does not meet verification or eligibility requirements.']},
  {title:'2. Booking Confirmation', body:['A booking is considered confirmed only after successful payment of the applicable booking amount and completion of required verification, wherever applicable.','Vehicle availability is subject to confirmation. If the booked vehicle becomes unavailable due to breakdown, accident, maintenance or another unavoidable reason, Ride Aura Self Drive may offer a similar available vehicle or provide an applicable refund.']},
  {title:'3. Security Deposit', body:['A refundable security deposit may be required depending on vehicle category, rental duration and booking conditions.','The deposit may be adjusted against vehicle damage, traffic fines, late return charges, missing fuel, excess kilometre charges, missing accessories or documents, excessive cleaning, towing/recovery expenses or other booking-related outstanding amounts.','Any remaining refundable amount will be processed after vehicle inspection and liability review.']},
  {title:'4. Vehicle Pickup & Return', body:['The customer must collect and return the vehicle at the agreed location, date and time.','Complimentary pickup facilities may be available at Bhubaneswar Airport and Bhubaneswar Railway Station, subject to booking confirmation, operational availability and applicable service conditions.','Late returns may result in additional charges.']},
  {title:'4A. Minimum Booking Duration', body:['Minimum booking duration for Ride Aura cars and bikes is 12 hours. Customers must choose pickup and return timings that meet the minimum 12-hour booking requirement.']},
  {title:'5. Authorised Driver', body:['Only the customer or another verified and authorised driver under the booking may drive the vehicle.','Allowing an unauthorised, unlicensed or underage person to drive the vehicle may result in immediate termination of the rental and additional liability.']},
  {title:'6. Permitted Use', body:['The vehicle must be used only for lawful personal or business travel.','The vehicle must not be used for racing, illegal activities, unauthorised commercial passenger transportation, intoxicated driving, reckless driving, prohibited goods, sub-renting or unsafe/prohibited areas without authorisation.']},
  {title:'7. Fuel Policy', body:['Unless specifically included in the selected rental plan, fuel expenses are the responsibility of the customer.','The vehicle should be returned according to the fuel policy communicated at booking. Any fuel shortage may be charged to the customer.']},
  {title:'8. Traffic Violations', body:['The customer is fully responsible for traffic violations, parking fines, toll violations, e-challans and penalties arising during the rental period.','If a challan is received after return but relates to the customer rental period, Ride Aura Self Drive reserves the right to recover the applicable amount.']},
  {title:'9. Accident, Damage & Breakdown', body:['In the event of accident, damage, theft or breakdown, the customer must immediately contact Ride Aura Self Drive.','The customer must not independently arrange major repairs without prior approval except in a genuine emergency.','Customer liability for damage depends on the incident, insurance coverage, exclusions and rental agreement. Damage caused by negligence, illegal driving, intoxication, unauthorised driving or term violation may become the customer responsibility.']},
  {title:'10. Vehicle Condition', body:['Customers are encouraged to inspect the vehicle at pickup and report visible existing damage.','The vehicle must be returned in reasonably similar condition, subject to normal wear and tear. Charges may apply for excessive damage, missing items, smoking damage, stains or unreasonable cleaning requirements.']},
  {title:'11. Travel Area', body:['Ride Aura Self Drive primarily provides services for customers travelling across Odisha.','Any interstate travel restrictions, permissions, additional charges or geographical limitations applicable to a booking will be communicated separately.','Restricted Areas: Phulbani, Koraput and Malkangiri belts in Odisha are restricted areas. Booking of a vehicle for trips in these areas will be treated as cancelled.']},
  {title:'12. Prohibited Activities', body:['General Restrictions: Customers are not allowed to carry arms, ammunitions, banned drugs or pets. Use of the vehicle for commercial activity such as product sale, promotion or carrying goods is strictly prohibited. In such cases, customers will be charged a penalty of Rs. 5000 or the penalty charged by the authorities, whichever is higher.','Specific Prohibitions: The vehicle must not be used for any speed race or competition; for towing, pushing, marriage use or propelling any trailer or other vehicle; for the primary business purpose of transporting people or operating a taxi service; by any person under the influence of alcohol, drugs or medication under which driving is prohibited or not recommended; or for committing any crime, illegal or unlawful activity.','Driver Authorization: Only the renter is authorised to drive the vehicle. If any other person is found driving the vehicle, or if the vehicle is sublet, the renter security money will be forfeited.','Vehicle Care: Smoking, drinking and all types of drugs are not allowed inside the vehicle. If anything related is found inside the vehicle, a charge of Rs. 2000 may apply.','Customers must not tamper with GPS devices, tracking systems, odometers, safety equipment or installed vehicle technology.']},
  {title:'13. Right to Recover Vehicle', body:['Ride Aura Self Drive reserves the right to recover or repossess the vehicle where there is suspected illegal activity, serious misuse, unauthorised extension, payment default, safety risk or material violation of rental terms.']},
  {title:'14. Personal Belongings', body:['Ride Aura Self Drive is not responsible for personal belongings lost, stolen or left inside the vehicle. Customers should check the vehicle carefully before returning it.']},
  {title:'15. Limitation of Liability', body:['To the extent permitted by applicable law, Ride Aura Self Drive is not responsible for indirect losses, missed flights, missed trains, business losses or travel disruptions caused by circumstances beyond reasonable operational control.']},
  {title:'16. Governing Law', body:['These Terms are governed by the applicable laws of India. Any disputes are subject to the jurisdiction of competent courts as determined under applicable law and the final rental agreement.']}
];

const policies = [
  {title:'Cancellation & Refund Policy', body:'Cancellation charges may depend on how early the booking is cancelled before scheduled pickup. Convenience fees, payment gateway charges or other non-refundable charges may be deducted where applicable. Approved refunds will be initiated to the original payment method or another mutually agreed method.'},
  {title:'No-Show Policy', body:'If a customer fails to collect the vehicle within the permitted pickup window without informing Ride Aura Self Drive, the booking may be treated as a no-show and applicable charges may be deducted.'},
  {title:'Cancellation by Ride Aura Self Drive', body:'If Ride Aura Self Drive is unable to provide the booked vehicle due to breakdown, accident, maintenance or operational issue, we will make reasonable efforts to provide a suitable alternative vehicle. If no suitable alternative is available, the applicable booking amount for the unavailable service will be refunded.'},
  {title:'Security Deposit Policy', body:'A security deposit may be collected before handover and may vary by vehicle category, rental duration, verification, booking type and applicable promotional plan. The deposit covers potential outstanding liabilities such as damage, fuel shortage, traffic violations and excessive cleaning.'},
  {title:'Privacy Policy', body:'Ride Aura Self Drive may collect customer information including name, mobile number, email, driving licence details, government-issued ID information, booking and travel information, payment information, vehicle usage information, device information and support communications to manage bookings, verification, payments, support, safety and legal requirements.'},
  {title:'Damage & Accident Policy', body:'Customer must immediately inform Ride Aura Self Drive in case of accident, vehicle damage, theft, mechanical breakdown, tyre damage, loss of keys or damage to vehicle documents/accessories. Customer must cooperate with police reporting, insurance documentation, photographs, videos and claim requirements where needed.'},
  {title:'Late Return & Booking Extension Policy', body:'Customers must return the vehicle at the scheduled time. If additional time is needed, an extension should be requested before the scheduled return time. Extensions are subject to availability, additional rental charges and approval.'},
  {title:'Fair Usage Policy', body:'Customers are expected to drive responsibly, follow traffic laws, keep the vehicle reasonably clean, avoid intentional or negligent damage, follow kilometre limits, return the vehicle on time and immediately inform Ride Aura Self Drive about accidents or mechanical issues.'}
];

export default function TermsPage(){return <main><section className="section terms-hero"><div className="container"><span className="eyebrow">Legal & Policies</span><h1>Ride Aura Self Drive Terms & Conditions</h1><p>Last Updated: July 2026</p><p>By booking, accessing or using a vehicle provided through Ride Aura Self Drive, the customer agrees to comply with these Terms & Conditions.</p></div></section><section className="section"><div className="container terms-grid">{sections.map(section=><article className="terms-card" key={section.title}><h2>{section.title}</h2>{section.body.map(item=><p key={item}>{item}</p>)}</article>)}</div></section><section className="section band"><div className="container"><div className="title"><span className="eyebrow">Policies</span><h2>Cancellation, Privacy, Damage and Fair Usage</h2></div><div className="terms-grid two">{policies.map(policy=><article className="terms-card" key={policy.title}><h2>{policy.title}</h2><p>{policy.body}</p></article>)}</div><div className="notice-card"><strong>Important Booking Notice:</strong> By confirming a booking with Ride Aura Self Drive, the customer acknowledges that they have read and accepted the applicable Terms & Conditions, Cancellation & Refund Policy, Security Deposit Policy, Privacy Policy, Damage & Accident Policy and Fair Usage Policy.</div></div></section><style>{`.terms-hero{background:linear-gradient(110deg,rgba(7,22,45,.94),rgba(7,22,45,.76)),linear-gradient(135deg,#fff8ec,#f5b846);color:#fff}.terms-hero h1{font-size:clamp(38px,5vw,62px);line-height:1;margin:12px 0}.terms-hero p{max-width:850px;color:#eef6ff;font-size:18px;line-height:1.65}.terms-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.terms-grid.two{grid-template-columns:repeat(2,1fr)}.terms-card{background:#fff;border:1px solid #e2e8f0;border-radius:14px;padding:22px;box-shadow:0 14px 34px rgba(15,23,42,.08)}.terms-card h2{margin:0 0 12px;color:#07162d;font-size:20px}.terms-card p{margin:0 0 12px;color:#5b6675;line-height:1.65}.notice-card{margin-top:24px;background:#fff8e7;border:1px solid #f4d48d;border-radius:14px;padding:20px;color:#5f3d00;line-height:1.7}@media(max-width:980px){.terms-grid,.terms-grid.two{grid-template-columns:1fr}}`}</style></main>}
